### ISSUE TITLE
ss88/easy_unsubscribe: package version disagreement between packagist and Roundcube Plugin Repository

### ISSUE THREAD

**Issue by emtiu** [roundcube/plugins2.roundcube.net#35]
The plugin ss88/easy_unsubscribe is listed at:
* https://plugins.roundcube.net/#/packages/ss88/easy_unsubscribe and
* https://packagist.org/packages/ss88/easy_unsubscribe

and both web frontends display https://github.com/SS88UK/roundcube-easy-unsubscribe/commit/3970c082f61c1bfbcad04fb86f881aab62189499 as the latest `dev-master` commit.

However, when using composer to install it, the information at https://plugins.roundcube.net/p/ss88/easy_unsubscribe%243eca1312a1595c6ebfe5e178c043d8ac8348a541df6381c8a9aea41b9f62b0d9.json is referenced by composer, which is outdated and lists [d09f442](https://github.com/SS88UK/roundcube-easy-unsubscribe/commit/d09f4428aeb6763dd4110a59e32cfcb231174c8b) from 2019 as the latest commit.

There must be something weird going on for the [Roundcube Plugins web frontend](https://plugins.roundcube.net/#/packages/ss88/easy_unsubscribe) and [its actual hosted json version information](https://plugins.roundcube.net/p/ss88/easy_unsubscribe%243eca1312a1595c6ebfe5e178c043d8ac8348a541df6381c8a9aea41b9f62b0d9.json) to disagree.

Because of this, I've found it impossible to install the latest version through composer.

**Comment by johndoh** [comment]
I guess this is related to https://roundcube.net/news/2020/04/11/changes-in-roundcubes-plugin-repository
> We’d like to make the switch on May 17th 2020. On this day, the repository data of plugins.roundcube.net will be frozen

It goes on to say
> Once a plugin is listed at packagist.org, Roundcube’s plugin repository will no longer list it in order to make packagist.org the only source.

but may be something went wrong? by now all plugins should be listed on packagist.org so if you remove https://plugins.roundcube.net from the repositories list in your composer.json then may be that will solve your issue.

**Comment by emtiu** [comment]
You're right! Removing this section from my composer.json:
```
"repositories": [
    {
        "type": "composer",
        "url": "https://plugins.roundcube.net"
    }
],
```
does the trick and updates easy_unsubscribe to the latest commit (with no ill side-effects I noticed).

But then why is that repo still part of the official `composer.json-dist`? 🤔

**Comment by johndoh** [comment]
may be because there is only the `dev-master` version of this plugin and plugins.roundcube.net has that version then composer uses it because its listed in your repositories list.

where as if there was a newer version of the plugin release. like plugins.roundcube.net had version 1.1 as its most recent version and packagist.org had a version 1.2 then it would automatically take the newer version? its just a guess.

any way I agree it might be time to take the old repo out of composer.json-dist. I opened https://github.com/roundcube/roundcubemail/issues/9323

**Comment by emtiu** [comment]
Roundcube hast removes `https://plugins.roundcube.net` from its `composer.json` now: https://github.com/roundcube/roundcubemail/commit/6ace57e8e1cb3f408e09478d8c57433d2c5ad57c … so I guess this problem will go away in time :)
